[package]
name = "eval_pythia"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
rayon = "1.10.0"
seq_io = "0.3.3"
serde = { version = "1.0.219", features = ["derive"] }

[profile.release]
debug = true
