build-master:
    docker build . -t muelllu9/jati
    docker push muelllu9/jati

build-hash hash:
    docker build --build-arg COMMIT_HASH={{hash}} . -t muelllu9/jati:{{hash}}
    docker push muelllu9/jati:{{hash}}

bench hash features:
    ssh austin.node "mkdir -p temp/{{hash}}/target && mkdir -p temp/{{hash}}/out && \
    cp -r temp/reference/criterion temp/{{hash}}/target && \
    cp temp/jati_bench.submit temp/{{hash}}/jati_bench.submit && \
    sbatch -o temp/{{hash}}/out/std.out --export=FEATURES="{{features}}",COMMIT_HASH="{{hash}}",HOME temp/{{hash}}/jati_bench.submit"

listen hash:
    ssh austin.node "tail -f temp/{{hash}}/out/std.out"

reset-reference:
    ssh austin.node "rm -rf temp/reference && mkdir -p temp/reference"
    scp jati_bench.submit austin.node:temp/jati_bench.submit
    scp -r reference austin.node:temp/

fetch-results hash:
    mkdir -p results/{{hash}}
    scp -r austin.node:temp/{{hash}}/target/criterion results/{{hash}}